#include<stdio.h>

int main(){
	printf("hi\n");
	return 0;
}




/*## This file is automatically generated from /etc/audit/rules.d
-D
-b 320

-a always,exit -F dir=/etc/audit/ -F uid>=1000 -F auid!=4294967295 -k USE
-a always,exit -F arch=b64 -S execve -k USE
-a always,exit -F arch=b32 -S execve -k USE
-a never,exit -F dir=/usr/lib/gcc/x86_64-linux-gnu
-a never,exit -S all -F subj_type=pulseaudio_t -F subj_type=ntpd_t -F subj_type=cron_t
-a never,user -F subj_type=crond_t
-a exit,never -F subj_type=crond_t
-a never,user -F subj_type=cron_t
-a exit,never -F subj_type=cron_t
-a never,exit -F dir=/var/cache
-a never,exit -F dir=/root/.cache
-a never,exit -F dir=/proc*/
